export type {
  UserId,
  UserRole,
  AuthUser,
  AuditLogEntry,
  RegisterRequestDto,
  RegisterResponseDto,
  LoginRequestDto,
  LoginResponseDto,
  RefreshResponseDto,
  MeResponseDto,
  ProfileResponseDto,
} from "./types/auth.js";

export type {
  CourseId,
  ModuleId,
  LessonId,
  CourseStatus,
  CourseLevel,
  LessonType,
  LessonQuizOption,
  LessonQuizQuestion,
  LessonQuiz,
  Course,
  CourseModule,
  Lesson,
  CreateCourseRequestDto,
  CourseResponseDto,
  ModuleResponseDto,
  LessonResponseDto,
  CourseDetailResponseDto,
  InstructorSummaryResponseDto,
  CourseCategoriesResponseDto,
  CreateModuleRequestDto,
  CreateLessonRequestDto,
  UpdateCourseRequestDto,
  ListCoursesResponseDto,
} from "./types/course.js";

export type {
  EnrollmentId,
  Enrollment,
  EnrollmentResponseDto,
  EnrollmentStatusResponseDto,
  EnrollmentListResponseDto,
  EnrollRequestDto,
} from "./types/enrollment.js";

export type {
  ProgressId,
  ProgressRecord,
  LessonCompletionRecord,
  WatchSnapshotRecord,
  VideoEventType,
  VideoEventRecord,
  ProgressResponseDto,
  SaveProgressRequestDto,
  MarkLessonCompleteRequestDto,
  WatchSnapshotRequestDto,
  VideoEventRequestDto,
  SaveProgressResponseDto,
  LessonCompletionResponseDto,
  WatchSnapshotResponseDto,
  VideoEventResponseDto,
  CourseProgressResponseDto,
  StudentCourseProgressDto,
  InstructorEngagementMetricsDto,
  InstructorCourseProgressResponseDto,
  StudentCourseSummaryDto,
  StudentDashboardTotalsDto,
  StudentDashboardResponseDto,
} from "./types/progress.js";

export type {
  PaymentId,
  PaymentStatus,
  PaymentRecord,
  WebhookEventRecord,
  CreateCheckoutRequestDto,
  CreateCheckoutResponseDto,
  PaymentWebhookRequestDto,
  PaymentWebhookResponseDto,
  PaymentStatusResponseDto,
  PaymentHistoryItemDto,
  PaymentHistoryResponseDto,
} from "./types/payment.js";

export type {
  PaginatedResponse,
  ApiErrorResponse,
  AdminUserDto,
  AdminUserListResponseDto,
} from "./types/api.js";
