export type {
  ProgressId,
  ProgressRecord,
  LessonCompletionRecord,
  WatchSnapshotRecord,
  VideoEventType,
  VideoEventRecord,
  ProgressResponseDto,
  SaveProgressRequestDto,
  MarkLessonCompleteRequestDto,
  WatchSnapshotRequestDto,
  VideoEventRequestDto,
  SaveProgressResponseDto,
  LessonCompletionResponseDto,
  WatchSnapshotResponseDto,
  VideoEventResponseDto,
  CourseProgressResponseDto,
  StudentCourseProgressDto,
  InstructorEngagementMetricsDto,
  InstructorCourseProgressResponseDto,
  StudentCourseSummaryDto,
  StudentDashboardTotalsDto,
  StudentDashboardResponseDto,
} from "@learnsphere/shared";
